### ISSUE TITLE
[plm_suspended] missing un suspend action

### ISSUE THREAD

**Issue by SalahAdDin** [OmniaGit/odooplm#13]
I am working to update these modules in a proper way to `Odoo 11`, and maybe also `12`; and i found a missing function in the code:
https://github.com/OmniaGit/odooplm/blob/11.0/plm_suspended/views/plm_product_view.xml#L20
it is the same thing in https://github.com/OmniaGit/odooplm/blob/11.0/plm_suspended/views/plm_document_view.xml#L19.

But that functions do not exist in the `python` code, why?

**Comment by OmniaGit** [comment]
this module is not finished yet. we just push the modification

**Comment by SalahAdDin** [comment]
@OmniaGit oh, really? But i added some improvements, can you review them?

**Comment by SalahAdDin** [comment]
@OmniaGit  i'm getting a bug related to this module:
![deepin-screen-recorder_select area_20180921084409](https://user-images.githubusercontent.com/5034215/45862543-db6fd800-bd7a-11e8-89f3-1f07ccf4dd4e.gif)

We can see the register of this actions in the messages:
![erdaproblemaconmodulo](https://user-images.githubusercontent.com/5034215/45862632-47524080-bd7b-11e8-93e8-3f46317a5aa5.png)

In some way, the functions implemented in this module overwrite the behavior of the other button, preventing the states from being changed or reflected in the user interface.
Any help?

Thank you.

**Comment by OmniaGit** [comment]
fixed in v12
