### ISSUE TITLE
[11.0][plm-automatic-weight] : wrong field in xml.

### ISSUE THREAD

**Issue by Vassy** [OmniaGit/odooplm#22]
In  odooplm/plm_automatic_weight/views/component_extension.xml line 30 **force_compute_bom_weight_action** is wrong. Please replace with **compute_bom_weight_action**

https://github.com/Vassy/odooplm/commit/3f93eec93cd0d57848b5ceba38ab4351392dcbde#diff-1209b2638ef53b2706f469e267d72494

**Comment by OmniaGit** [comment]
fixed
