### ISSUE TITLE
[11.0]odooplm 2d print pdf

### ISSUE THREAD

**Issue by PaulWang52** [OmniaGit/odooplm#25]
Hello

I can't print 2d pdf, how to solve it, thank you 

![PLM-1](https://user-images.githubusercontent.com/49329222/55663665-f6f08b00-5853-11e9-8561-5ad838babbd3.jpg)
![PLM-2](https://user-images.githubusercontent.com/49329222/55663666-f7892180-5853-11e9-9d94-111bc1dbf247.jpg)
![PLM-3](https://user-images.githubusercontent.com/49329222/55663667-f7892180-5853-11e9-9c80-96e78e8f25e7.jpg)
![PLM-4](https://user-images.githubusercontent.com/49329222/55663668-f7892180-5853-11e9-9608-c5695bda17a7.jpg)
![PLM-5](https://user-images.githubusercontent.com/49329222/55663669-f7892180-5853-11e9-8e5a-8d169ae62478.jpg)

**Comment by OmniaGit** [comment]
Dear Paul,
could you please give us more details on how to reproduce the problem ?
The screen shut are not clear
which cad are you using to perform the save operation ?
did you save the file with our integration ?
which version of odoo are you using ?
you get some error ?

regards
Matteo

**Comment by PaulWang52** [comment]
Dear Matteo,
Sorry,My English is very poor
I use solid edge
Yes，I use your integration save
Odoo v11
In documents print pdf 2d，but it is blank.

![PLM-1](https://user-images.githubusercontent.com/49329222/55669754-ca695d00-58ad-11e9-8593-5c32602350c9.jpg)
![PLM-2](https://user-images.githubusercontent.com/49329222/55669755-cb01f380-58ad-11e9-9a2a-3a3fbf9bed58.jpg)
![PLM-3](https://user-images.githubusercontent.com/49329222/55669756-cb01f380-58ad-11e9-8c04-26ed49f6e017.jpg)
![PLM-4](https://user-images.githubusercontent.com/49329222/55669757-cb01f380-58ad-11e9-9c83-c6000652ee49.jpg)
![PLM-5](https://user-images.githubusercontent.com/49329222/55669758-cb9a8a00-58ad-11e9-8428-b11d284944c8.jpg)

**Comment by OmniaGit** [comment]
did you solve the problem ?
