### ISSUE TITLE
Document - record can be saved even though no file has been added

### ISSUE THREAD

**Issue by duplomatic-anava** [OmniaGit/odooplm#35]
A document record can be saved even if no file has been selected. In my opinion, we should not be able to save if a file is not present; upon creation, revision, always.

If needed, I can solve the issue with a pull request.

Thank you in advance.

Alessio

**Comment by OmniaGit** [comment]
it's correct in this way, most of the time in the migration to odooPLM from another plm we strongly use this 

> feature

regards
Matteo
 ..

**Comment by duplomatic-anava** [comment]
Alright Matteo, thank you for the hint. I was just referring to the web interface, not making it a required database field.

It may make sense to create the document name and then upload the file later on the web interface, so we can leave it as it is right now.

Thank you,

Alessio
