### ISSUE TITLE
Implementation ideas - Document categories

### ISSUE THREAD

**Issue by duplomatic-anava** [OmniaGit/odooplm#39]
Dear @OmniaGit ,

internally, we are planning to create document categories following the scheme for product categories. Is this something you would like to see merged in this repo too?

So that all documents belonging to a certain category (quality, manufacturing, etc.) can be filtered.

Let me know.

Alessio

**Comment by OmniaGit** [comment]
Thanks,
but  for the moment we do not have any request in this terms.
also saving file from the cad application will impact on this too, so we prefer to leave it as it is

regards,
Matteo

**Comment by duplomatic-anava** [comment]
Alright Matteo, I will leave a branch in our public fork in case you changed your mind in the future :)

Alessio

**Comment by OmniaGit** [comment]
Thanks any way ..
regards,
Matteo
