### ISSUE TITLE
PLM spare install error（odoo12 Enterprise version）

### ISSUE THREAD

**Issue by anviz-github** [OmniaGit/odooplm#51]
Element '<group name="doc_user">' cannot be located in parent view

Error context:
View `ir.attachment.spare.extension`
[view_id: 4964, xml_id: n/a, model: ir.attachment, parent_id: 4904]
None" while parsing /home/odoo/src/user/odooplm-12.0/plm_spare/views/ir_attachment_view.xml:3, near
<record id="ir_attachment_spare_extension" model="ir.ui.view">
        <field name="name">ir.attachment.spare.extension</field>
        <field name="model">ir.attachment</field>
        <field name="inherit_id" ref="plm.view_attachment_form_plm_hinerit"/>
        <field name="type">form</field>
        <field name="priority" eval="16"/>
        <field name="arch" type="xml">
            <group name="doc_user" position="inside">
                <field string="Spare Part" name="used_for_spare" attrs="{'readonly':[('state','in',['released','obsoleted'])]}"/>
            </group>
        </field>
    </record>
<img width="1440" alt="Screen Shot 2020-03-09 at 2 28 57 PM" src="https://user-images.githubusercontent.com/54052406/76188154-58626c00-6212-11ea-9dcf-676cf51cf41d.png">

**Comment by OmniaGit** [comment]
Thanks for you report, we fix the issues with this commit 9e7fbe4b38a99bca9dddd547797a04b21c5e4210

thanks for the report
