### ISSUE TITLE
[11.0] Service product have engineering information.

### ISSUE THREAD

**Issue by SalahAdDin** [OmniaGit/odooplm#6]
We are using this module in an Industry Manufacturing company and i am testing it trying to adapt it to our workflow.

Company manufacture engineering peace that also can be stockable for future sale orders, but i see that only services and consumable products can be related to an Engineering Part.

Why?

I think it is related to the **MO** concept, right?

**Comment by OmniaGit** [comment]
as designed only stockable and consumable product could be selected.. engineering shuld accept only this kind of products

regards
Matteo

**Comment by SalahAdDin** [comment]
No, stockable products do not handle engineering info. Services and consumables can handle it.

**Comment by SalahAdDin** [comment]
I didn't see the button before, i'm sorry.
But, for now, it stills show the button for services:
![deepin-screen-recorder_select area_20180921140440](https://user-images.githubusercontent.com/5034215/45877718-77173d80-bda7-11e8-8012-987c3eba02fb.gif)

**Comment by OmniaGit** [comment]
fix in v12
