### ISSUE TITLE
Integration with Windchill

### ISSUE THREAD

**Issue by max3903** [OmniaGit/odooplm#61]
**Is your feature request related to a problem? Please describe.**

I have a customer interested to integrate Windchill with OdooPLM.
https://www.ptc.com/en/products/windchill

**Describe the solution you'd like**

Coming soon...

**Describe alternatives you've considered**

Coming soon...

**Additional context**

Coming soon...

**Comment by OmniaGit** [comment]
OdooPLM is mean to be use as PLM.
for windchill there is the api for extracting product and bom
