### ISSUE TITLE
Feature Request: Client without CAD integration

### ISSUE THREAD

**Issue by tomquinn04** [OmniaGit/odooplm#63]
**Is your feature request related to a problem? Please describe.** I would like to use the PLM client with PTC Creo but also other programs such as photoshop.

**Describe the solution you'd like** A dropbox-style version where I can check out a file and it will be downloaded into a folder where I can edit it.

**Describe alternatives you've considered** Sharepoint, but this does not have the project management features.

**Additional context** n/a

**Comment by OmniaGit** [comment]
> **Is your feature request related to a problem? Please describe.** I would like to use the PLM client with PTC Creo but also other programs such as photoshop.
We can make the integration for you if your application has api com interface. we have a lot of request for Creo. mey be in the near feature we will create it.
> 
> **Describe the solution you'd like** A dropbox-style version where I can check out a file and it will be downloaded into a folder where I can edit it.
> 
have a look at https://www.omniasolutions.website/page/plm-box
> 
> **Describe alternatives you've considered** Sharepoint, but this does not have the project management features.
>
no we will use odoo as base document managment 
>
> **Additional context** n/a
