### ISSUE TITLE
Part image in Odoo 14 not updated after part is modified

### ISSUE THREAD

**Issue by etoimene** [OmniaGit/odooplm#67]
**Describe the bug** A clear and concise description of what the bug is.
We change part geometry in SolidWorks 2022 and after save in Odoo (tried check-in too) part image on LinkedDocuments tab is not updated.

**To Reproduce** Steps to reproduce the behavior:

1. We change part geometry in SolidWorks 2022
2. Using PLM Save button we save it to Odoo

**Expected behavior** A clear and concise description of what you expected to happen.
LinkedDocuments image should be like new geometry.

**Screenshots** If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

- OS: Win10
- Browser : any

**Additional context** Add any other context about the problem here.

**Comment by OmniaGit** [comment]
Dear,

did you save locally(solidworks) before save into add-in application ?
there is also an option on the client that make the save operation for you, does this setting is enabled ?

in order to further investigate on your behaviour we need to know the client version that are you using (complete name of the installer)

thanks for your report

**Comment by etoimene** [comment]
Thanks for your great product. :)

We have explicitly saved part using SolidWorks before attempting PLM Save.
Not sure which setting is needed for this automated save operation.
I will update PLM client version info when I get access to it, but downloaded from sourceforge in the last 40-50 days, so fairly recent.

**Comment by etoimene** [comment]
![image](https://user-images.githubusercontent.com/93099253/163959925-23476f5c-5d52-4eb0-9393-f03402380290.png)
Here is the version. We used OdooPlm_2019_odoov13_21012022_162934.exe to install.

**Comment by OmniaGit** [comment]
Update  your odooplm modules from github on odoo server performing un upgrade on the plm module
download the latest client at this link https://sourceforge.net/projects/openerpplm/files/Client/Candidate/OdooPlm_2019_odoov13_31032022_095826.exe/download
the system should work out of the box.

let me know if it fix the problem
regards

**Comment by etoimene** [comment]
For some parts it works, for some not. 
With newly added parts, there are no problems (as far as I can see).

We installed the client you suggested and have Odoo modules.
"Module Name","Technical Name","Latest Version","Status"
"Product Lifecycle Management","plm","14.0.2","Installed"
"PLM Automate Normal Bom","plm_automate_normal_bom","14.0.1.0.0","Installed"
"PLM Compare Bom","plm_compare_bom","14.0.1.0.0","Installed"
"PLM Engineering","plm_engineering","14.0.1.0.0","Installed"

**Comment by etoimene** [comment]
Do you have any new suggestion?

**Comment by OmniaGit** [comment]
be sure that all your parts has the right property set up 
use the https://odooplm.omniasolutions.website/login#Edit-Parts for each part of your cad application.

once all is set if you click on the save button the plugin save the assembly.

in order to check your assembly before to save set the option as in the screen shot

![2022-04-29_16-53](https://user-images.githubusercontent.com/14873448/165969612-303166ed-7e8f-4302-aa71-1824f335a7aa.png)
a new windows appear and be sure that all the column have the right data
 
![2022-04-29_17-00](https://user-images.githubusercontent.com/14873448/165970931-1a39ec31-4a13-4785-961b-bf42f0908801.png)

hope it helps
regards

**Comment by etoimene** [comment]
That is set. Without that, it is impossible to save the part in first place.

Can you suggest what should I look for in eg. application.log?

It works on some parts and not on other, so my process is OK, but I think some properties are different.

I will check as you suggested. Maybe I didn't see something obvious before.

**Comment by etoimene** [comment]
Odoo Part and  Solidworks file are saved correctly, but image is missing. Maybe image name has some strange characters or it is attempted to be stored somewhere on the client where it shouldn't be ...

**Comment by OmniaGit** [comment]
for the image you need to set properly windows explorer in order to upload the preview.

![2022-04-29_17-57](https://user-images.githubusercontent.com/14873448/165980921-b3f5f9c1-b639-4d54-8e9b-5d2c9b23b77d.png)
 
regards

**Comment by etoimene** [comment]
Oooh, great! That makes sense. 
It always uploads the latest thumbnail?

**Comment by OmniaGit** [comment]
Yes, during the saving procedure CAD-> odoo we extract the preview from the files and upload it
regards

**Comment by etoimene** [comment]
I tried again and with new parts it works as expected.

Parts that are already in the Odoo without those images do not get new images, despite correct thumbnail update on Windows file explorer.

**Comment by OmniaGit** [comment]
the file that has no change is not updated.
the system in order to be very smart upload only the files that are changed.

regards,
Matteo

**Comment by etoimene** [comment]
From what I can see, Windows explorer thumbnail was updated, but not DB. We did not change part name (engineering code).
I'll give it another test.

What do you consider change?

**Comment by OmniaGit** [comment]
it means that the file date is changed, than the client application will upload the new image to odoo using the save button

regards,
Matteo

**Comment by etoimene** [comment]
Thanks! Somehow I thought timestamp is used.
I will make another round of tests. Maybe on the different PC.

**Comment by etoimene** [comment]
Some new info.
We have 2 things that could influence this.
1. odoo server is not synced with ntp
2. Thumbnails on this machine are sometimes changed, sometimes not

I'll investigate further and post result here.

**Comment by etoimene** [comment]
After ntp sync issues on one machine are gone.
Other one is still bugging us. That one beheves strangely in general, so might be some Windows issue.

**Comment by OmniaGit** [comment]
I  close the issue ..
reopen it in case of any further problem
