### ISSUE TITLE
fixed batch size in work orders

### ISSUE THREAD

**Issue by samuelosram** [OmniaGit/odooplm#72]
We try to use MRP. And we use PLM. So we hope we get maybe here a answer. Thx.

We produce items with a fix batch size. Means we can produce at once eg 50 items. Or a multiple of it. 100, 150.

Work orders will created always with a number of items computed from reorder rules or mto etc. We see no possiblity to change work order to the next "batch size". Eg reorder rule want order 10 items, mrp should be capable to change the number of items to a fixed number (or a multible of it).

I hope our needing is understandable. Is this possible?

**Comment by OmniaGit** [comment]
Dear @samuelosram ,

this is not plm related problem, it's better  to ask to the oca manufactory :https://github.com/OCA/manufacture

may be they have develop already somethings that cover your problem.

regards
