### ISSUE TITLE
plm_pdf_workorder - Client not generating PDF from Solidworks .SLDDRW

### ISSUE THREAD

**Issue by j540** [OmniaGit/odooplm#73]
When saving a 2D drawing in Solidworks 2022, the OdooPLM client successfully uploads the .slddrw drawing to odoo v15 enterprise, but does not create a .pdf version for viewing in plm_pdf_workorder.

Is there an alternative way to upload the PDF, such that it can viewed in the tablet workorder view?

Thank you.

**Comment by OmniaGit** [comment]
dear @j540 ,
If you save the 2d solidworks document from the client application, the pdf must be present in odoo.
You can try the print it from product -> print -> print attached PDF
If the document is available, than it's also available from the workdorder.

Be sure to give a part number at your file and that you save it with the client.
Also you need to the **Use PLM PDF** boolen to be set inside the workorder

regards
